MailNdLogging/Controllers/EmailController.cs
using MailNdLogging.Messaging;
using MailNdLogging.Models;
using System.Configuration;
using System.Web.Mvc;

namespace MailNdLogging.Controllers
{
    public class EmailController : Controller
    {

        [HttpGet]
         public ActionResult SendEmail()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendEmail(SendEmail sm)
        {
            string key = ConfigurationManager.AppSettings["Sendgrid.Key"];
            SendGridEmailService messageSvc = new SendGridEmailService(key);

            string htmlBody = $@"<ul>
                                <li>Name: {sm.Name}</li>    
                                <li>Email: {sm.Email}</li>
                                <li>Message Details: {sm.Message}</li>
                            </ul>";

            var msg = new EmailMsg()
            {
                Body = htmlBody,
                Subject = sm.Subject,
                From = sm.Name,
                Recipient = sm.Email
            };

            return RedirectToAction("Success", "Home");

            //messageSvc.SendMail(msg, true, fileName, fileData);
            //var fileName = FileConverter.GetFilePath("Logs\\2018-05-21.log");
            //var fileData = FileConverter.Convert(fileName);
            //attaches file
            //string envPath = HttpRuntime.AppDomainAppPath;
            //string fileName = $"{envPath}\\Content\\assets\\images\\logo_dark.png";
            //byte[] imageData = null;
            //FileInfo fileInfo = new FileInfo(fileName);
            //long imageFileLength = fileInfo.Length;
            //FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            //BinaryReader br = new BinaryReader(fs);
            //imageData = br.ReadBytes((int)imageFileLength);

            //messageSvc.SendMail(msg, true, fileName, imageData);


        }
    }
}

MailNdLogging/Controllers/LogErrorController.cs
using MailNdLogging.Helpers;
using MailNdLogging.Messaging;
using MailNdLogging.Models;
using NLog;
using System;
using System.Configuration;
using System.Web.Mvc;



[assembly: log4net.Config.XmlConfigurator(Watch = true)]
namespace MailNdLogging.Controllers
{
    public class LogErrorController : Controller
    {
        
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public ActionResult Log4net()
        {
            log.Error("This is our error message");
            try
            {
                int i = 5;
                var s = i / 0;
            }
            catch (DivideByZeroException ex)
            {
                log.Fatal("This was a terrible error");
                log.Debug("Here again", ex);
            }

            return View();
        }


        [HttpPost]
        public ActionResult Log4net(SendEmail sm)
        {
            string key = ConfigurationManager.AppSettings["Sendgrid.Key"];
            SendGridEmailService messageSvc = new SendGridEmailService(key);

            string htmlBody = $@"<ul>
                                <li>Name: {sm.Name}</li>    
                                <li>Email: {sm.Email}</li>
                                <li>Message Details: {sm.Message}</li>
                            </ul>";

            var msg = new EmailMsg()
            {
                Body = htmlBody,
                Subject = sm.Subject,
                From = sm.Name,
                Recipient = sm.Email
            };

            var fileName = FileConverter.GetFilePath("Log\\Log-file.txt");
            var fileData = FileConverter.Convert(fileName);



            messageSvc.SendMail(msg, true, fileName, fileData);



            return RedirectToAction("Success", "Home");

            //attaches file
            //string envPath = HttpRuntime.AppDomainAppPath;
            //string fileName = $"{envPath}\\Content\\assets\\images\\logo_dark.png";
            //byte[] imageData = null;
            //FileInfo fileInfo = new FileInfo(fileName);
            //long imageFileLength = fileInfo.Length;
            //FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            //BinaryReader br = new BinaryReader(fs);
            //imageData = br.ReadBytes((int)imageFileLength);

            //messageSvc.SendMail(msg, true, fileName, imageData);


        }




        // GET: LogError
        public ActionResult NLog()
        {
            try
            {
                int i = 5;
                var s = i / 0;
            }
            catch (DivideByZeroException ex)
            {
                Logger logger = LogManager.GetCurrentClassLogger();

                logger.Error(ex, "this too");

            }

            return View();
        }

        [HttpPost]
        public ActionResult NLog(SendEmail sm)
        {
            string key = ConfigurationManager.AppSettings["Sendgrid.Key"];
            SendGridEmailService messageSvc = new SendGridEmailService(key);

            string htmlBody = $@"<ul>
                                <li>Name: {sm.Name}</li>    
                                <li>Email: {sm.Email}</li>
                                <li>Message Details: {sm.Message}</li>
                            </ul>";

            var msg = new EmailMsg()
            {
                Body = htmlBody,
                Subject = sm.Subject,
                From = sm.Name,
                Recipient = sm.Email
            };

            var fileName = FileConverter.GetFilePath("Logs\\2018-05-21.log");
            var fileData = FileConverter.Convert(fileName);



            messageSvc.SendMail(msg, true, fileName, fileData);



            return RedirectToAction("Success", "Home");

            //attaches file
            //string envPath = HttpRuntime.AppDomainAppPath;
            //string fileName = $"{envPath}\\Content\\assets\\images\\logo_dark.png";
            //byte[] imageData = null;
            //FileInfo fileInfo = new FileInfo(fileName);
            //long imageFileLength = fileInfo.Length;
            //FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            //BinaryReader br = new BinaryReader(fs);
            //imageData = br.ReadBytes((int)imageFileLength);

            //messageSvc.SendMail(msg, true, fileName, imageData);


        }



    }
}

MailNdLogging/Controllers/LoginAuthController.cs
using MailNdLogging.Models;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace MailNdLogging.Controllers
{

    public class LoginAuthController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(LoginInfo loginInfo)
        {
            
            var email = "admin@admin.com";
            var password = "admin";

            if (ModelState.IsValid && email==loginInfo.Email && password == loginInfo.Password)
            {
                
                ClaimsIdentity claimsIdentity = new ClaimsIdentity("ApplicationCookie");
                claimsIdentity.AddClaim(new Claim(ClaimTypes.Email, loginInfo.Email));
                var context = Request.GetOwinContext();
                context.Authentication.SignIn(claimsIdentity);

                return RedirectToAction("Index","Home");

            }
            else
                ModelState.AddModelError("", "Invalid Username or Password");


            return View(loginInfo);

        }

        public ActionResult Signout()
        {
            var context = Request.GetOwinContext();
            context.Authentication.SignOut("ApplicationCookie");
            return Redirect("Login");
        }


    }



}

MailNdLogging/Views/Shared/_AuthLayout.cshtml
@{
    Layout = null;
}
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/Content/img/favicon.png">
    <link rel="icon" type="image/png" href="~/Content/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Login Page</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/material-kit.css" rel="stylesheet" />
</head>
<body>



    @RenderBody()
    <!--   Core JS Files   -->
    <script src="~/Content/js/jquery.min.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Content/js/material.min.js"></script>

    <!--    Plugin for Date Time Picker and Full Calendar Plugin   -->
    <script src="~/Content/js/moment.min.js"></script>

    <!--	Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/   -->
    <script src="~/Content/js/nouislider.min.js" type="text/javascript"></script>


    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select   -->
    <script src="~/Content/js/bootstrap-selectpicker.js" type="text/javascript"></script>

    <!--	Plugin for Tags, full documentation here: http://xoxco.com/projects/code/tagsinput/   -->
    <script src="~/Contents/js/bootstrap-tagsinput.js"></script>


    <!--    Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc    -->
    <script src="~/Content/js/material-kit.js?v=1.2.1" type="text/javascript"></script>
</body>

MailNdLogging/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/Content/img/favicon.png">
    <link rel="icon" type="image/png" href="~/Content/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>HomePage</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/material-kit.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

        <ul class="nav navbar-nav navbar-right">



            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"
                   id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Logs
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="@Url.Action("NLog","LogError")">Nlog</a></li>
                    <li><a class="dropdown-item" href="@Url.Action("Log4net","LogError")">Log 4 Net</a></li>
                    <li><a class="dropdown-item" href="@Url.Action("SendEmail","Email")">Send Mail</a></li>
                    
                    <li role="separator" class="divider"></li>
                    <li><a href="@Url.Action("Signout","LoginAuth")"><i class="icon ion-power"></i> Sign Out</a></li>
                </ul>
            </li>


        </ul>


        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MailLogger", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - emChristos</p>
        </footer>
    </div>

    <!--   Core JS Files   -->
    <script src="~/Content/js/jquery.min.js" type="text/javascript"></script>
    <script src="~/Content/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Content/js/material.min.js"></script>

    <!--    Plugin for Date Time Picker and Full Calendar Plugin   -->
    <script src="~/Content/js/moment.min.js"></script>

    <!--	Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/   -->
    <script src="~/Content/js/nouislider.min.js" type="text/javascript"></script>
    <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker   -->
    <script src="~/Content/js/bootstrap-datetimepicker.js" type="text/javascript"></script>


    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select   -->
    <script src="~/Content/js/bootstrap-selectpicker.js" type="text/javascript"></script>

    <!--	Plugin for Tags, full documentation here: http://xoxco.com/projects/code/tagsinput/   -->
    <script src="~/Contents/js/bootstrap-tagsinput.js"></script>

    <!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput   -->
    <script src="~/Contents/js/jasny-bootstrap.min.js"></script>

    <!--    Plugin For Google Maps   -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>


    <!--    Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc    -->
    <script src="~/Content/js/material-kit.js?v=1.2.1" type="text/javascript"></script>
</body>
</html>